In [1]:
from keras.utils import np_utils
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from sklearn import datasets

Using TensorFlow backend.


In [2]:
iris = datasets.load_iris()

In [3]:
iris.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [4]:
iris['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [5]:
iris['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [6]:
iris['data']

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
import pandas as pd
d_iris = pd.DataFrame(iris['data'], columns=iris['feature_names'])
d_iris

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [9]:
x=iris['data']
y=iris['target']
x_train, x_test, y_train, y_test=train_test_split(x, y, test_size=0.2, random_state=1)
#訓練0.8 測試0.2
print(x_test)

[[5.8 4.  1.2 0.2]
 [5.1 2.5 3.  1.1]
 [6.6 3.  4.4 1.4]
 [5.4 3.9 1.3 0.4]
 [7.9 3.8 6.4 2. ]
 [6.3 3.3 4.7 1.6]
 [6.9 3.1 5.1 2.3]
 [5.1 3.8 1.9 0.4]
 [4.7 3.2 1.6 0.2]
 [6.9 3.2 5.7 2.3]
 [5.6 2.7 4.2 1.3]
 [5.4 3.9 1.7 0.4]
 [7.1 3.  5.9 2.1]
 [6.4 3.2 4.5 1.5]
 [6.  2.9 4.5 1.5]
 [4.4 3.2 1.3 0.2]
 [5.8 2.6 4.  1.2]
 [5.6 3.  4.5 1.5]
 [5.4 3.4 1.5 0.4]
 [5.  3.2 1.2 0.2]
 [5.5 2.6 4.4 1.2]
 [5.4 3.  4.5 1.5]
 [6.7 3.  5.  1.7]
 [5.  3.5 1.3 0.3]
 [7.2 3.2 6.  1.8]
 [5.7 2.8 4.1 1.3]
 [5.5 4.2 1.4 0.2]
 [5.1 3.8 1.5 0.3]
 [6.1 2.8 4.7 1.2]
 [6.3 2.5 5.  1.9]]


In [10]:
y_trainOneHot = np_utils.to_categorical(y_train)
y_testOneHot = np_utils.to_categorical(y_test)
print(y_testOneHot)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
#建立模型
model = Sequential()
model.add(Dense(units=120,
                input_dim=4,
                kernel_initializer='normal',
                activation='relu'))
model.add(Dense(units=3,
                kernel_initializer='normal',
                activation='softmax'))

In [12]:
print(model.summary())

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 120)               600       
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 363       
Total params: 963
Trainable params: 963
Non-trainable params: 0
_________________________________________________________________
None


In [13]:
#訓練模型
model.compile(loss='categorical_crossentropy',
              optimizer='adam',metrics=['accuracy'])

In [18]:
train_history= model.fit(x=x_train,
                         y=y_trainOneHot,validation_split=0.35,
                         epochs=20, batch_size=120,
                         verbose=2)

Train on 78 samples, validate on 42 samples
Epoch 1/20
 - 0s - loss: 0.5163 - acc: 0.7051 - val_loss: 0.5431 - val_acc: 0.6667
Epoch 2/20
 - 0s - loss: 0.5115 - acc: 0.7051 - val_loss: 0.5376 - val_acc: 0.6667
Epoch 3/20
 - 0s - loss: 0.5067 - acc: 0.7051 - val_loss: 0.5319 - val_acc: 0.6667
Epoch 4/20
 - 0s - loss: 0.5020 - acc: 0.7051 - val_loss: 0.5263 - val_acc: 0.6667
Epoch 5/20
 - 0s - loss: 0.4974 - acc: 0.7051 - val_loss: 0.5207 - val_acc: 0.6667
Epoch 6/20
 - 0s - loss: 0.4929 - acc: 0.7051 - val_loss: 0.5153 - val_acc: 0.6905
Epoch 7/20
 - 0s - loss: 0.4886 - acc: 0.7051 - val_loss: 0.5101 - val_acc: 0.6905
Epoch 8/20
 - 0s - loss: 0.4843 - acc: 0.7051 - val_loss: 0.5052 - val_acc: 0.6905
Epoch 9/20
 - 0s - loss: 0.4802 - acc: 0.7051 - val_loss: 0.5005 - val_acc: 0.7143
Epoch 10/20
 - 0s - loss: 0.4761 - acc: 0.7179 - val_loss: 0.4961 - val_acc: 0.7381
Epoch 11/20
 - 0s - loss: 0.4720 - acc: 0.7308 - val_loss: 0.4919 - val_acc: 0.7381
Epoch 12/20
 - 0s - loss: 0.4681 - acc: 0